version: 2.1

executors:
  builder:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  nightly-base:
    executor: builder
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: "19.03.8"
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Build & Push Images
          environment:
            DOCKER_BUILDKIT: 1
          command: |
            tag="$(git rev-parse --short HEAD)"
            docker build --progress=plain -t "$DOCKERHUB_USERNAME/mavenexample:${tag}" myapp
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/mavenexample:$TAG
      - save_cache:
          key: v1-pkg-cache
          paths:
            - ~/.cache/go-build

workflows:
  version: 2
  nightly-base:
    jobs:
      - nightly-base:
          filters:
            branches:
              only: master
